# Use uma imagem base do Python
FROM python:3.8

# Defina o diretório de trabalho como /app
WORKDIR /app

# Copie o conteúdo local para o diretório /app
COPY . /app

# Instale as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Exponha a porta 5000
EXPOSE 5000

# Comando para executar a aplicação quando o contêiner for iniciado
CMD ["python", "app.py"]
